name: Issue assigned sync

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  issues:
    types: [edited]
  schedule:
    - cron: '*/15 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Get issue comments
      uses: dgounaris/git-jira-assign-action@master
      with:
        jiraBaseUrl: ${{ secrets.JIRA_BASE_URL }}
        jiraEmail: ${{ secrets.JIRA_USER_EMAIL }}
        jiraToken: ${{ secrets.JIRA_API_TOKEN }}
        token: ${{ secrets.GTOKEN }}
        owner: dgounaris
        repository: test-jira-actions
