# This is a basic workflow to help you get started with Actions

name: Jira

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  issues:
    types: [opened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
    - name: Jira Login
      uses: atlassian/gajira-login@v2.0.0
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        
    - name: Jira Create issue
      id: create
      uses: dgounaris/gajira-create@master
      with:
        jiraBaseUrl: ${{ secrets.JIRA_BASE_URL }}
        # Key of the project
        project: DPG
        # Type of the issue to be created. Example: 'Incident'
        issuetype: Bug
        # Issue summary
        summary: ${{ github.event.issue.title }}
        label: community
        jiraEmail: ${{ secrets.JIRA_USER_EMAIL }}
        jiraToken: ${{ secrets.JIRA_API_TOKEN }}
        # Issue description
        description: |
          ${{ github.event.issue.body }}
          
          Created by github action.
          
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.GTOKEN }}
        issue-number: ${{ github.event.issue.number }}
        body: |
          Automatically created Jira issue: ${{ steps.create.outputs.issue }}
        reaction-type: '+1'
        
    - name: Send mail
      uses: dawidd6/action-send-mail@master
      with:
        server_address: smtp.office365.com
        server_port: 587
        username: ${{ secrets.DG_MAIL_USER }}
        password: ${{ secrets.DG_MAIL_PASS }}
        subject: Github Actions job result
        # Literal body:
        body: |
          Created new issue 
          ${{ steps.create.outputs.issue.title }}

          ${{ steps.create.outputs.issue.summary }}
        to: dgoungr@hotmail.com
        from: DG
        # Optional content type (defaults to text/plain):
        content_type: text/html
