name: Issue close sync

on:
  issues:
    types: [edited]
  schedule:
    - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync 
      uses: dgounaris/git-jira-action@master
      with:
        project: DPG
        jiraBaseUrl: ${{ secrets.JIRA_BASE_URL }}
        jiraEmail: ${{ secrets.JIRA_USER_EMAIL }}
        jiraToken: ${{ secrets.JIRA_API_TOKEN }}
        token: ${{ secrets.GTOKEN }}
        owner: dgounaris
        repository: test-jira-actions
